### ISSUE TITLE
How I can explore files as ROOT?

### ISSUE THREAD

**Issue by hamedsbt** [ibilux/MobyDroid#11]
Hi, I've ROOTED phone with Android Q
The adb was granted ROOT access and adb shell (terminal) **su** works and **Su Root Permission** option in active but I can change level up in File-Manager and it stuck on \sdcard with empty file list!

**Comment by ibilux** [comment]
@hamedsbt Should be fixed in v0.4

**Comment by mr-gittes** [comment]
still v0.4 doesn't work on android 10 rooted with magisk  and root permissions set in app: when accessing some root folders (e.g. /efs) there are no files shown inside...!? it seems the app has adb without root. only adb (root) shell works...
