### ISSUE TITLE
Add drag & drop support

### ISSUE THREAD

**Issue by WolfgangFahl** [ibilux/MobyDroid#3]
This looks promising.
Drag & Drop support would be very useful

**Comment by ibilux** [comment]
Hello @WolfgangFahl,
Drag & Drop is already supported in "App installer".
You can simply Drag & Drop apk files to the "MobyDroid" to add them to the install apps list.

If you have any further suggestions, please let us know.
We appreciate all helpful suggestions. 

Regards,

**Comment by WolfgangFahl** [comment]
Thx for looking into this.
Sorry - i was referencing the Filemanager not the App installer
