### ISSUE TITLE
adb devices can see my phone but not mobydroid

### ISSUE THREAD

**Issue by tyler820201** [ibilux/MobyDroid#6]
I am using Kubuntu 18.04 LTS Android Studio adb repo installed. If i run adb devices in terminal i can see the connected devices but i can not see on mobydroid

**Comment by ibilux** [comment]
What version of MobyDroid you are using ?

**Comment by tyler820201** [comment]
I am using the latest v 0.2

**Comment by tyler820201** [comment]
Is that any chanche to be able to run from the Terminal this OnePlus3&3T-ToolKit-v5.0U-By-@ahmed_radaideh toolikit? Unfortunatelly this is an .img file and i haveto use VirtualBox as on Linux does not work...

**Comment by ibilux** [comment]
I'm glad for that.
