### ISSUE TITLE
terminal  .bat file running

### ISSUE THREAD

**Issue by tyler820201** [ibilux/MobyDroid#7]
Is that any chanche to be able to run from the Terminal this OnePlus3&3T-ToolKit-v5.0U-By-@ahmed_radaideh toolikit? Unfortunatelly this is an .bat file and i have to use VirtualBox as on Linux does not work...

**Comment by ibuprophen1** [comment]
There's a few ways to make this happen but, I can't state what is the best direction to go. 

I believe that the following link should provide you with ideas for this. 

https://superuser.com/questions/712712/how-can-i-start-a-virtualbox-vm-and-then-run-a-batch-file-inside-the-vm

Good Luck! :-) 


~Ibuprophen
