### ISSUE TITLE
Dependency is not satisfiable: android-tools | On ubuntu 18.04

### ISSUE THREAD

**Issue by gech2me** [ibilux/MobyDroid#8]
$ sudo gdebi mobydroid_v0.2-1.deb

Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: android-tools

**Comment by ibilux** [comment]
try to install `android-tools` on ubuntu 18.04:

> sudo apt-get install android-tools-adb android-tools-fastboot

**Comment by gech2me** [comment]
> try to install `android-tools` on ubuntu 18.04:
> 
> > sudo apt-get install android-tools-adb android-tools-fastboot

Thanks for the reply. Nothing changed.
Here is the output.
```
gech@x:workspace$ sudo apt-get install android-tools-adb android-tools-fastboot
[sudo] password for gech:            
Reading package lists... Done
Building dependency tree       
Reading state information... Done
android-tools-adb is already the newest version (1:8.1.0+r23-5~18.04).
android-tools-fastboot is already the newest version (1:8.1.0+r23-5~18.04).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
gech@x:workspace$ cd
gech@x:~$ cd Downloads
gech@x:Downloads$ cd Prog*
gech@x:Programs$ ls
4kvideodownloader_4.7.3-1_amd64.deb  build                  mobydroid_v0.2-1_1.deb                                   proxpn_4.5.0.0_amd64.deb
aom                                  franz_5.1.0_amd64.deb  mseinstall.exe                                           rufus-3.5p.exe
aom-tools_1.0.0-2_amd64.deb          Gradianto_New.jar      mysql-workbench-community_8.0.16-1ubuntu18.04_amd64.deb  vlc-3.0.7.1
gech@x:Programs$ sudo gdebi moby*.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: android-tools
```

**Comment by ibilux** [comment]
try to download, extract and run the jar file:
`java -jar "mobydroid.jar"`

Link:
https://github.com/ibilux/MobyDroid/releases/download/v0.2/mobydroid.jar

**Comment by gech2me** [comment]
That does not work.

Here is the output
```
getachew@hp:Programs$ ls
mobydroid.jar
getachew@hp:Programs$ java mobydroid.jar
Error: Could not find or load main class mobydroid.jar
Caused by: java.lang.ClassNotFoundException: mobydroid.jar
getachew@hp:Programs$ 
```
Thanks.

**Comment by ibilux** [comment]
> That does not work.
> 
> Here is the output
> 
> ```
> getachew@hp:Programs$ ls
> mobydroid.jar
> getachew@hp:Programs$ java mobydroid.jar
> Error: Could not find or load main class mobydroid.jar
> Caused by: java.lang.ClassNotFoundException: mobydroid.jar
> getachew@hp:Programs$ 
> ```
> 
> Thanks.

You forget to add `-jar` to the command line to run the jar file:
`java -jar "mobydroid.jar"`

try again with `-jar`.

**Comment by gech2me** [comment]
That works. Thanks.
